namespace Lunggo.Hotel.ViewModels
{
    public class HotelFacilities
    {
        public bool Spa { get; set; }
        public bool Sauna { get; set; }
        public bool Jacuzzi { get; set; }
        public bool Fitness { get; set; }
        public bool Gymnasium { get; set; }
        public bool Field { get; set; }
        public bool Tennis { get; set; }
        public bool IndoorPool { get; set; }
        public bool OutdoorPool { get; set; }
        public bool TableTennis { get; set; }
        public bool KidsClub { get; set; }
        public bool Billiard { get; set; }
        public bool GameCorner { get; set; }
        public bool Karaoke { get; set; }
        public bool BanquetHall { get; set; }
        public bool BBQ { get; set; }
        public bool DryRoom { get; set; }
        public bool Restaurant { get; set; }
        public bool CoffeeShop { get; set; }
        public bool ConvenienceStore { get; set; }
        public bool Bar { get; set; }
        public bool Lounge { get; set; }
        public bool BusinessCenter { get; set; }
        public bool ConferenceRoom { get; set; }
        public bool NonSmokingRooms { get; set; }
        public bool IceMakingMachine { get; set; }
        public bool LobbyWifi { get; set; }
        public bool MorningCall { get; set; }
        public bool LayananKamar { get; set; }
        public bool CleaningService { get; set; }
        public bool Esthetics { get; set; }
        public bool Massage { get; set; }
        public bool RentalCycle { get; set; }
        public bool VoltageConverter { get; set; }
        public bool Golf { get; set; }
        public bool PuttingGolf { get; set; }
        public bool Fishing { get; set; }
        public bool Paraglider { get; set; }
        public bool HorseRiding { get; set; }
        public bool Diving { get; set; }
        public bool Rafting { get; set; }
        public bool Canoe { get; set; }
        public bool LANConnection { get; set; }
        public bool WirelessLAN { get; set; }
        public bool PCRental { get; set; }
        public bool FreeInternet { get; set; }
        public bool BathRoomForAllrooms { get; set; }
        public bool ShowerForAllRooms { get; set; }
        public bool BathubForAllRooms { get; set; }
        public bool ACForAllRooms { get; set; }
        public bool TV { get; set; }
        public bool BSBroadcast { get; set; }
        public bool Refrigerator { get; set; }
        public bool MiniBar { get; set; }
        public bool KitchenForAllRooms { get; set; }
        public bool TrouserPress { get; set; }
        public bool SafetyBox { get; set; }
        public bool HandTowel { get; set; }
        public bool Toothbrush { get; set; }
        public bool BathTowel { get; set; }
        public bool Shampoo { get; set; }
        public bool HairConditioner { get; set; }
        public bool BodySoap { get; set; }
        public bool Soap { get; set; }
        public bool Pajamas { get; set; }
        public bool Bathrobe { get; set; }
        public bool Sandal { get; set; }
        public bool HairDryer { get; set; }
        public bool Shaver { get; set; }
        public bool ShowerCap { get; set; }
        public bool Cottonbud { get; set; }
        public bool ShowerToilet { get; set; }
        public bool Comb { get; set; }
    }
}
