//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.OnePointService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="Mystifly.OnePoint", ConfigurationName="OnePointService.OnePoint")]
    public interface OnePoint {
        
        [System.ServiceModel.OperationContractAttribute(Action="Mystifly.OnePoint/OnePoint/CreateSession", ReplyAction="Mystifly.OnePoint/OnePoint/CreateSessionResponse")]
        MystiflyOnePointAPI.OnePointService.SessionCreateRS CreateSession(MystiflyOnePointAPI.OnePointService.SessionCreateRQ rq);
        
        [System.ServiceModel.OperationContractAttribute(Action="Mystifly.OnePoint/OnePoint/CreateSession", ReplyAction="Mystifly.OnePoint/OnePoint/CreateSessionResponse")]
        System.Threading.Tasks.Task<MystiflyOnePointAPI.OnePointService.SessionCreateRS> CreateSessionAsync(MystiflyOnePointAPI.OnePointService.SessionCreateRQ rq);
        
        [System.ServiceModel.OperationContractAttribute(Action="Mystifly.OnePoint/OnePoint/EndSession", ReplyAction="Mystifly.OnePoint/OnePoint/EndSessionResponse")]
        bool EndSession(string SessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="Mystifly.OnePoint/OnePoint/EndSession", ReplyAction="Mystifly.OnePoint/OnePoint/EndSessionResponse")]
        System.Threading.Tasks.Task<bool> EndSessionAsync(string SessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="Mystifly.OnePoint/OnePoint/AirLowFareSearch", ReplyAction="Mystifly.OnePoint/OnePoint/AirLowFareSearchResponse")]
        MystiflyOnePointAPI.OnePointService.AirLowFareSearchRS AirLowFareSearch(MystiflyOnePointAPI.OnePointService.AirLowFareSearchRQ rq);
        
        [System.ServiceModel.OperationContractAttribute(Action="Mystifly.OnePoint/OnePoint/AirLowFareSearch", ReplyAction="Mystifly.OnePoint/OnePoint/AirLowFareSearchResponse")]
        System.Threading.Tasks.Task<MystiflyOnePointAPI.OnePointService.AirLowFareSearchRS> AirLowFareSearchAsync(MystiflyOnePointAPI.OnePointService.AirLowFareSearchRQ rq);
        
        [System.ServiceModel.OperationContractAttribute(Action="Mystifly.OnePoint/OnePoint/AirRevalidate", ReplyAction="Mystifly.OnePoint/OnePoint/AirRevalidateResponse")]
        MystiflyOnePointAPI.OnePointService.AirRevalidateRS AirRevalidate(MystiflyOnePointAPI.OnePointService.AirRevalidateRQ rq);
        
        [System.ServiceModel.OperationContractAttribute(Action="Mystifly.OnePoint/OnePoint/AirRevalidate", ReplyAction="Mystifly.OnePoint/OnePoint/AirRevalidateResponse")]
        System.Threading.Tasks.Task<MystiflyOnePointAPI.OnePointService.AirRevalidateRS> AirRevalidateAsync(MystiflyOnePointAPI.OnePointService.AirRevalidateRQ rq);
        
        [System.ServiceModel.OperationContractAttribute(Action="Mystifly.OnePoint/OnePoint/BookFlight", ReplyAction="Mystifly.OnePoint/OnePoint/BookFlightResponse")]
        MystiflyOnePointAPI.OnePointService.AirBookRS BookFlight(MystiflyOnePointAPI.OnePointService.AirBookRQ rq);
        
        [System.ServiceModel.OperationContractAttribute(Action="Mystifly.OnePoint/OnePoint/BookFlight", ReplyAction="Mystifly.OnePoint/OnePoint/BookFlightResponse")]
        System.Threading.Tasks.Task<MystiflyOnePointAPI.OnePointService.AirBookRS> BookFlightAsync(MystiflyOnePointAPI.OnePointService.AirBookRQ rq);
        
        [System.ServiceModel.OperationContractAttribute(Action="Mystifly.OnePoint/OnePoint/FareRules", ReplyAction="Mystifly.OnePoint/OnePoint/FareRulesResponse")]
        MystiflyOnePointAPI.OnePointService.AirRulesRS FareRules(MystiflyOnePointAPI.OnePointService.AirRulesRQ rq);
        
        [System.ServiceModel.OperationContractAttribute(Action="Mystifly.OnePoint/OnePoint/FareRules", ReplyAction="Mystifly.OnePoint/OnePoint/FareRulesResponse")]
        System.Threading.Tasks.Task<MystiflyOnePointAPI.OnePointService.AirRulesRS> FareRulesAsync(MystiflyOnePointAPI.OnePointService.AirRulesRQ rq);
        
        [System.ServiceModel.OperationContractAttribute(Action="Mystifly.OnePoint/OnePoint/CancelBooking", ReplyAction="Mystifly.OnePoint/OnePoint/CancelBookingResponse")]
        MystiflyOnePointAPI.OnePointService.AirCancelRS CancelBooking(MystiflyOnePointAPI.OnePointService.AirCancelRQ rq);
        
        [System.ServiceModel.OperationContractAttribute(Action="Mystifly.OnePoint/OnePoint/CancelBooking", ReplyAction="Mystifly.OnePoint/OnePoint/CancelBookingResponse")]
        System.Threading.Tasks.Task<MystiflyOnePointAPI.OnePointService.AirCancelRS> CancelBookingAsync(MystiflyOnePointAPI.OnePointService.AirCancelRQ rq);
        
        [System.ServiceModel.OperationContractAttribute(Action="Mystifly.OnePoint/OnePoint/TicketOrder", ReplyAction="Mystifly.OnePoint/OnePoint/TicketOrderResponse")]
        MystiflyOnePointAPI.OnePointService.AirOrderTicketRS TicketOrder(MystiflyOnePointAPI.OnePointService.AirOrderTicketRQ rq);
        
        [System.ServiceModel.OperationContractAttribute(Action="Mystifly.OnePoint/OnePoint/TicketOrder", ReplyAction="Mystifly.OnePoint/OnePoint/TicketOrderResponse")]
        System.Threading.Tasks.Task<MystiflyOnePointAPI.OnePointService.AirOrderTicketRS> TicketOrderAsync(MystiflyOnePointAPI.OnePointService.AirOrderTicketRQ rq);
        
        [System.ServiceModel.OperationContractAttribute(Action="Mystifly.OnePoint/OnePoint/TripDetails", ReplyAction="Mystifly.OnePoint/OnePoint/TripDetailsResponse")]
        MystiflyOnePointAPI.OnePointService.AirTripDetailsRS TripDetails(MystiflyOnePointAPI.OnePointService.AirTripDetailsRQ rq);
        
        [System.ServiceModel.OperationContractAttribute(Action="Mystifly.OnePoint/OnePoint/TripDetails", ReplyAction="Mystifly.OnePoint/OnePoint/TripDetailsResponse")]
        System.Threading.Tasks.Task<MystiflyOnePointAPI.OnePointService.AirTripDetailsRS> TripDetailsAsync(MystiflyOnePointAPI.OnePointService.AirTripDetailsRQ rq);
        
        [System.ServiceModel.OperationContractAttribute(Action="Mystifly.OnePoint/OnePoint/AddBookingNotes", ReplyAction="Mystifly.OnePoint/OnePoint/AddBookingNotesResponse")]
        MystiflyOnePointAPI.OnePointService.AirBookingNotesRS AddBookingNotes(MystiflyOnePointAPI.OnePointService.AirBookingNotesRQ rq);
        
        [System.ServiceModel.OperationContractAttribute(Action="Mystifly.OnePoint/OnePoint/AddBookingNotes", ReplyAction="Mystifly.OnePoint/OnePoint/AddBookingNotesResponse")]
        System.Threading.Tasks.Task<MystiflyOnePointAPI.OnePointService.AirBookingNotesRS> AddBookingNotesAsync(MystiflyOnePointAPI.OnePointService.AirBookingNotesRQ rq);
        
        [System.ServiceModel.OperationContractAttribute(Action="Mystifly.OnePoint/OnePoint/MessageQueues", ReplyAction="Mystifly.OnePoint/OnePoint/MessageQueuesResponse")]
        MystiflyOnePointAPI.OnePointService.AirMessageQueueRS MessageQueues(MystiflyOnePointAPI.OnePointService.AirMessageQueueRQ rq);
        
        [System.ServiceModel.OperationContractAttribute(Action="Mystifly.OnePoint/OnePoint/MessageQueues", ReplyAction="Mystifly.OnePoint/OnePoint/MessageQueuesResponse")]
        System.Threading.Tasks.Task<MystiflyOnePointAPI.OnePointService.AirMessageQueueRS> MessageQueuesAsync(MystiflyOnePointAPI.OnePointService.AirMessageQueueRQ rq);
        
        [System.ServiceModel.OperationContractAttribute(Action="Mystifly.OnePoint/OnePoint/RemoveMessageQueues", ReplyAction="Mystifly.OnePoint/OnePoint/RemoveMessageQueuesResponse")]
        MystiflyOnePointAPI.OnePointService.AirRemoveMessageQueueRS RemoveMessageQueues(MystiflyOnePointAPI.OnePointService.AirRemoveMessageQueueRQ rq);
        
        [System.ServiceModel.OperationContractAttribute(Action="Mystifly.OnePoint/OnePoint/RemoveMessageQueues", ReplyAction="Mystifly.OnePoint/OnePoint/RemoveMessageQueuesResponse")]
        System.Threading.Tasks.Task<MystiflyOnePointAPI.OnePointService.AirRemoveMessageQueueRS> RemoveMessageQueuesAsync(MystiflyOnePointAPI.OnePointService.AirRemoveMessageQueueRQ rq);
        
        [System.ServiceModel.OperationContractAttribute(Action="Mystifly.OnePoint/OnePoint/AirSeatMap", ReplyAction="Mystifly.OnePoint/OnePoint/AirSeatMapResponse")]
        MystiflyOnePointAPI.OnePointService.AirSeatMapRS AirSeatMap(MystiflyOnePointAPI.OnePointService.AirSeatMapRQ rq);
        
        [System.ServiceModel.OperationContractAttribute(Action="Mystifly.OnePoint/OnePoint/AirSeatMap", ReplyAction="Mystifly.OnePoint/OnePoint/AirSeatMapResponse")]
        System.Threading.Tasks.Task<MystiflyOnePointAPI.OnePointService.AirSeatMapRS> AirSeatMapAsync(MystiflyOnePointAPI.OnePointService.AirSeatMapRQ rq);
        
        [System.ServiceModel.OperationContractAttribute(Action="Mystifly.OnePoint/OnePoint/AirSeatReserve", ReplyAction="Mystifly.OnePoint/OnePoint/AirSeatReserveResponse")]
        MystiflyOnePointAPI.OnePointService.AirSeatRS AirSeatReserve(MystiflyOnePointAPI.OnePointService.AirSeatRQ rq);
        
        [System.ServiceModel.OperationContractAttribute(Action="Mystifly.OnePoint/OnePoint/AirSeatReserve", ReplyAction="Mystifly.OnePoint/OnePoint/AirSeatReserveResponse")]
        System.Threading.Tasks.Task<MystiflyOnePointAPI.OnePointService.AirSeatRS> AirSeatReserveAsync(MystiflyOnePointAPI.OnePointService.AirSeatRQ rq);
        
        [System.ServiceModel.OperationContractAttribute(Action="Mystifly.OnePoint/OnePoint/AirBookingData", ReplyAction="Mystifly.OnePoint/OnePoint/AirBookingDataResponse")]
        MystiflyOnePointAPI.OnePointService.AirBookingDataRS AirBookingData(MystiflyOnePointAPI.OnePointService.AirBookingDataRQ rq);
        
        [System.ServiceModel.OperationContractAttribute(Action="Mystifly.OnePoint/OnePoint/AirBookingData", ReplyAction="Mystifly.OnePoint/OnePoint/AirBookingDataResponse")]
        System.Threading.Tasks.Task<MystiflyOnePointAPI.OnePointService.AirBookingDataRS> AirBookingDataAsync(MystiflyOnePointAPI.OnePointService.AirBookingDataRQ rq);
        
        [System.ServiceModel.OperationContractAttribute(Action="Mystifly.OnePoint/OnePoint/MultiAirRevalidate", ReplyAction="Mystifly.OnePoint/OnePoint/MultiAirRevalidateResponse")]
        MystiflyOnePointAPI.OnePointService.MultiAirRevalidateRS MultiAirRevalidate(MystiflyOnePointAPI.OnePointService.MultiAirRevalidateRQ rq);
        
        [System.ServiceModel.OperationContractAttribute(Action="Mystifly.OnePoint/OnePoint/MultiAirRevalidate", ReplyAction="Mystifly.OnePoint/OnePoint/MultiAirRevalidateResponse")]
        System.Threading.Tasks.Task<MystiflyOnePointAPI.OnePointService.MultiAirRevalidateRS> MultiAirRevalidateAsync(MystiflyOnePointAPI.OnePointService.MultiAirRevalidateRQ rq);
        
        [System.ServiceModel.OperationContractAttribute(Action="Mystifly.OnePoint/OnePoint/MultiAirBookFlight", ReplyAction="Mystifly.OnePoint/OnePoint/MultiAirBookFlightResponse")]
        MystiflyOnePointAPI.OnePointService.MultiAirBookRS MultiAirBookFlight(MystiflyOnePointAPI.OnePointService.MultiAirBookRQ rq);
        
        [System.ServiceModel.OperationContractAttribute(Action="Mystifly.OnePoint/OnePoint/MultiAirBookFlight", ReplyAction="Mystifly.OnePoint/OnePoint/MultiAirBookFlightResponse")]
        System.Threading.Tasks.Task<MystiflyOnePointAPI.OnePointService.MultiAirBookRS> MultiAirBookFlightAsync(MystiflyOnePointAPI.OnePointService.MultiAirBookRQ rq);
        
        [System.ServiceModel.OperationContractAttribute(Action="Mystifly.OnePoint/OnePoint/IntelliFareSearch", ReplyAction="Mystifly.OnePoint/OnePoint/IntelliFareSearchResponse")]
        MystiflyOnePointAPI.OnePointService.AirLowFareSearchRS IntelliFareSearch(MystiflyOnePointAPI.OnePointService.IntelliFareRQ rq);
        
        [System.ServiceModel.OperationContractAttribute(Action="Mystifly.OnePoint/OnePoint/IntelliFareSearch", ReplyAction="Mystifly.OnePoint/OnePoint/IntelliFareSearchResponse")]
        System.Threading.Tasks.Task<MystiflyOnePointAPI.OnePointService.AirLowFareSearchRS> IntelliFareSearchAsync(MystiflyOnePointAPI.OnePointService.IntelliFareRQ rq);
        
        [System.ServiceModel.OperationContractAttribute(Action="Mystifly.OnePoint/OnePoint/IntelliBestBuy", ReplyAction="Mystifly.OnePoint/OnePoint/IntelliBestBuyResponse")]
        MystiflyOnePointAPI.OnePointService.AirLowFareSearchRS IntelliBestBuy(MystiflyOnePointAPI.OnePointService.IntelliBestBuyRQ rq);
        
        [System.ServiceModel.OperationContractAttribute(Action="Mystifly.OnePoint/OnePoint/IntelliBestBuy", ReplyAction="Mystifly.OnePoint/OnePoint/IntelliBestBuyResponse")]
        System.Threading.Tasks.Task<MystiflyOnePointAPI.OnePointService.AirLowFareSearchRS> IntelliBestBuyAsync(MystiflyOnePointAPI.OnePointService.IntelliBestBuyRQ rq);
        
        [System.ServiceModel.OperationContractAttribute(Action="Mystifly.OnePoint/OnePoint/AirQuote", ReplyAction="Mystifly.OnePoint/OnePoint/AirQuoteResponse")]
        MystiflyOnePointAPI.OnePointService.AirQuoteRS AirQuote(MystiflyOnePointAPI.OnePointService.AirQuoteRQ rq);
        
        [System.ServiceModel.OperationContractAttribute(Action="Mystifly.OnePoint/OnePoint/AirQuote", ReplyAction="Mystifly.OnePoint/OnePoint/AirQuoteResponse")]
        System.Threading.Tasks.Task<MystiflyOnePointAPI.OnePointService.AirQuoteRS> AirQuoteAsync(MystiflyOnePointAPI.OnePointService.AirQuoteRQ rq);
        
        [System.ServiceModel.OperationContractAttribute(Action="Mystifly.OnePoint/OnePoint/FareRules1_1", ReplyAction="Mystifly.OnePoint/OnePoint/FareRules1_1Response")]
        MystiflyOnePointAPI.OnePointService.AirRulesRS1 FareRules1_1(MystiflyOnePointAPI.OnePointService.AirRulesRQ1 rq);
        
        [System.ServiceModel.OperationContractAttribute(Action="Mystifly.OnePoint/OnePoint/FareRules1_1", ReplyAction="Mystifly.OnePoint/OnePoint/FareRules1_1Response")]
        System.Threading.Tasks.Task<MystiflyOnePointAPI.OnePointService.AirRulesRS1> FareRules1_1Async(MystiflyOnePointAPI.OnePointService.AirRulesRQ1 rq);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OnePointChannel : Test.OnePointService.OnePoint, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OnePointClient : System.ServiceModel.ClientBase<Test.OnePointService.OnePoint>, Test.OnePointService.OnePoint {
        
        public OnePointClient() {
        }
        
        public OnePointClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OnePointClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OnePointClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OnePointClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MystiflyOnePointAPI.OnePointService.SessionCreateRS CreateSession(MystiflyOnePointAPI.OnePointService.SessionCreateRQ rq) {
            return base.Channel.CreateSession(rq);
        }
        
        public System.Threading.Tasks.Task<MystiflyOnePointAPI.OnePointService.SessionCreateRS> CreateSessionAsync(MystiflyOnePointAPI.OnePointService.SessionCreateRQ rq) {
            return base.Channel.CreateSessionAsync(rq);
        }
        
        public bool EndSession(string SessionId) {
            return base.Channel.EndSession(SessionId);
        }
        
        public System.Threading.Tasks.Task<bool> EndSessionAsync(string SessionId) {
            return base.Channel.EndSessionAsync(SessionId);
        }
        
        public MystiflyOnePointAPI.OnePointService.AirLowFareSearchRS AirLowFareSearch(MystiflyOnePointAPI.OnePointService.AirLowFareSearchRQ rq) {
            return base.Channel.AirLowFareSearch(rq);
        }
        
        public System.Threading.Tasks.Task<MystiflyOnePointAPI.OnePointService.AirLowFareSearchRS> AirLowFareSearchAsync(MystiflyOnePointAPI.OnePointService.AirLowFareSearchRQ rq) {
            return base.Channel.AirLowFareSearchAsync(rq);
        }
        
        public MystiflyOnePointAPI.OnePointService.AirRevalidateRS AirRevalidate(MystiflyOnePointAPI.OnePointService.AirRevalidateRQ rq) {
            return base.Channel.AirRevalidate(rq);
        }
        
        public System.Threading.Tasks.Task<MystiflyOnePointAPI.OnePointService.AirRevalidateRS> AirRevalidateAsync(MystiflyOnePointAPI.OnePointService.AirRevalidateRQ rq) {
            return base.Channel.AirRevalidateAsync(rq);
        }
        
        public MystiflyOnePointAPI.OnePointService.AirBookRS BookFlight(MystiflyOnePointAPI.OnePointService.AirBookRQ rq) {
            return base.Channel.BookFlight(rq);
        }
        
        public System.Threading.Tasks.Task<MystiflyOnePointAPI.OnePointService.AirBookRS> BookFlightAsync(MystiflyOnePointAPI.OnePointService.AirBookRQ rq) {
            return base.Channel.BookFlightAsync(rq);
        }
        
        public MystiflyOnePointAPI.OnePointService.AirRulesRS FareRules(MystiflyOnePointAPI.OnePointService.AirRulesRQ rq) {
            return base.Channel.FareRules(rq);
        }
        
        public System.Threading.Tasks.Task<MystiflyOnePointAPI.OnePointService.AirRulesRS> FareRulesAsync(MystiflyOnePointAPI.OnePointService.AirRulesRQ rq) {
            return base.Channel.FareRulesAsync(rq);
        }
        
        public MystiflyOnePointAPI.OnePointService.AirCancelRS CancelBooking(MystiflyOnePointAPI.OnePointService.AirCancelRQ rq) {
            return base.Channel.CancelBooking(rq);
        }
        
        public System.Threading.Tasks.Task<MystiflyOnePointAPI.OnePointService.AirCancelRS> CancelBookingAsync(MystiflyOnePointAPI.OnePointService.AirCancelRQ rq) {
            return base.Channel.CancelBookingAsync(rq);
        }
        
        public MystiflyOnePointAPI.OnePointService.AirOrderTicketRS TicketOrder(MystiflyOnePointAPI.OnePointService.AirOrderTicketRQ rq) {
            return base.Channel.TicketOrder(rq);
        }
        
        public System.Threading.Tasks.Task<MystiflyOnePointAPI.OnePointService.AirOrderTicketRS> TicketOrderAsync(MystiflyOnePointAPI.OnePointService.AirOrderTicketRQ rq) {
            return base.Channel.TicketOrderAsync(rq);
        }
        
        public MystiflyOnePointAPI.OnePointService.AirTripDetailsRS TripDetails(MystiflyOnePointAPI.OnePointService.AirTripDetailsRQ rq) {
            return base.Channel.TripDetails(rq);
        }
        
        public System.Threading.Tasks.Task<MystiflyOnePointAPI.OnePointService.AirTripDetailsRS> TripDetailsAsync(MystiflyOnePointAPI.OnePointService.AirTripDetailsRQ rq) {
            return base.Channel.TripDetailsAsync(rq);
        }
        
        public MystiflyOnePointAPI.OnePointService.AirBookingNotesRS AddBookingNotes(MystiflyOnePointAPI.OnePointService.AirBookingNotesRQ rq) {
            return base.Channel.AddBookingNotes(rq);
        }
        
        public System.Threading.Tasks.Task<MystiflyOnePointAPI.OnePointService.AirBookingNotesRS> AddBookingNotesAsync(MystiflyOnePointAPI.OnePointService.AirBookingNotesRQ rq) {
            return base.Channel.AddBookingNotesAsync(rq);
        }
        
        public MystiflyOnePointAPI.OnePointService.AirMessageQueueRS MessageQueues(MystiflyOnePointAPI.OnePointService.AirMessageQueueRQ rq) {
            return base.Channel.MessageQueues(rq);
        }
        
        public System.Threading.Tasks.Task<MystiflyOnePointAPI.OnePointService.AirMessageQueueRS> MessageQueuesAsync(MystiflyOnePointAPI.OnePointService.AirMessageQueueRQ rq) {
            return base.Channel.MessageQueuesAsync(rq);
        }
        
        public MystiflyOnePointAPI.OnePointService.AirRemoveMessageQueueRS RemoveMessageQueues(MystiflyOnePointAPI.OnePointService.AirRemoveMessageQueueRQ rq) {
            return base.Channel.RemoveMessageQueues(rq);
        }
        
        public System.Threading.Tasks.Task<MystiflyOnePointAPI.OnePointService.AirRemoveMessageQueueRS> RemoveMessageQueuesAsync(MystiflyOnePointAPI.OnePointService.AirRemoveMessageQueueRQ rq) {
            return base.Channel.RemoveMessageQueuesAsync(rq);
        }
        
        public MystiflyOnePointAPI.OnePointService.AirSeatMapRS AirSeatMap(MystiflyOnePointAPI.OnePointService.AirSeatMapRQ rq) {
            return base.Channel.AirSeatMap(rq);
        }
        
        public System.Threading.Tasks.Task<MystiflyOnePointAPI.OnePointService.AirSeatMapRS> AirSeatMapAsync(MystiflyOnePointAPI.OnePointService.AirSeatMapRQ rq) {
            return base.Channel.AirSeatMapAsync(rq);
        }
        
        public MystiflyOnePointAPI.OnePointService.AirSeatRS AirSeatReserve(MystiflyOnePointAPI.OnePointService.AirSeatRQ rq) {
            return base.Channel.AirSeatReserve(rq);
        }
        
        public System.Threading.Tasks.Task<MystiflyOnePointAPI.OnePointService.AirSeatRS> AirSeatReserveAsync(MystiflyOnePointAPI.OnePointService.AirSeatRQ rq) {
            return base.Channel.AirSeatReserveAsync(rq);
        }
        
        public MystiflyOnePointAPI.OnePointService.AirBookingDataRS AirBookingData(MystiflyOnePointAPI.OnePointService.AirBookingDataRQ rq) {
            return base.Channel.AirBookingData(rq);
        }
        
        public System.Threading.Tasks.Task<MystiflyOnePointAPI.OnePointService.AirBookingDataRS> AirBookingDataAsync(MystiflyOnePointAPI.OnePointService.AirBookingDataRQ rq) {
            return base.Channel.AirBookingDataAsync(rq);
        }
        
        public MystiflyOnePointAPI.OnePointService.MultiAirRevalidateRS MultiAirRevalidate(MystiflyOnePointAPI.OnePointService.MultiAirRevalidateRQ rq) {
            return base.Channel.MultiAirRevalidate(rq);
        }
        
        public System.Threading.Tasks.Task<MystiflyOnePointAPI.OnePointService.MultiAirRevalidateRS> MultiAirRevalidateAsync(MystiflyOnePointAPI.OnePointService.MultiAirRevalidateRQ rq) {
            return base.Channel.MultiAirRevalidateAsync(rq);
        }
        
        public MystiflyOnePointAPI.OnePointService.MultiAirBookRS MultiAirBookFlight(MystiflyOnePointAPI.OnePointService.MultiAirBookRQ rq) {
            return base.Channel.MultiAirBookFlight(rq);
        }
        
        public System.Threading.Tasks.Task<MystiflyOnePointAPI.OnePointService.MultiAirBookRS> MultiAirBookFlightAsync(MystiflyOnePointAPI.OnePointService.MultiAirBookRQ rq) {
            return base.Channel.MultiAirBookFlightAsync(rq);
        }
        
        public MystiflyOnePointAPI.OnePointService.AirLowFareSearchRS IntelliFareSearch(MystiflyOnePointAPI.OnePointService.IntelliFareRQ rq) {
            return base.Channel.IntelliFareSearch(rq);
        }
        
        public System.Threading.Tasks.Task<MystiflyOnePointAPI.OnePointService.AirLowFareSearchRS> IntelliFareSearchAsync(MystiflyOnePointAPI.OnePointService.IntelliFareRQ rq) {
            return base.Channel.IntelliFareSearchAsync(rq);
        }
        
        public MystiflyOnePointAPI.OnePointService.AirLowFareSearchRS IntelliBestBuy(MystiflyOnePointAPI.OnePointService.IntelliBestBuyRQ rq) {
            return base.Channel.IntelliBestBuy(rq);
        }
        
        public System.Threading.Tasks.Task<MystiflyOnePointAPI.OnePointService.AirLowFareSearchRS> IntelliBestBuyAsync(MystiflyOnePointAPI.OnePointService.IntelliBestBuyRQ rq) {
            return base.Channel.IntelliBestBuyAsync(rq);
        }
        
        public MystiflyOnePointAPI.OnePointService.AirQuoteRS AirQuote(MystiflyOnePointAPI.OnePointService.AirQuoteRQ rq) {
            return base.Channel.AirQuote(rq);
        }
        
        public System.Threading.Tasks.Task<MystiflyOnePointAPI.OnePointService.AirQuoteRS> AirQuoteAsync(MystiflyOnePointAPI.OnePointService.AirQuoteRQ rq) {
            return base.Channel.AirQuoteAsync(rq);
        }
        
        public MystiflyOnePointAPI.OnePointService.AirRulesRS1 FareRules1_1(MystiflyOnePointAPI.OnePointService.AirRulesRQ1 rq) {
            return base.Channel.FareRules1_1(rq);
        }
        
        public System.Threading.Tasks.Task<MystiflyOnePointAPI.OnePointService.AirRulesRS1> FareRules1_1Async(MystiflyOnePointAPI.OnePointService.AirRulesRQ1 rq) {
            return base.Channel.FareRules1_1Async(rq);
        }
    }
}
